import { ColorScheme } from "@/hooks/useTheme";
import { StyleSheet } from "react-native";

export const createHomeStyles = (colors: ColorScheme) => {
  const styles = StyleSheet.create({
    container: {
      flex: 1,
    },
    safeArea: {
      flex: 1,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: "center",
      alignItems: "center",
    },
    loadingText: {
      marginTop: 20,
      fontSize: 18,
      fontWeight: "500",
      color: colors.text,
    },
    header: {
      paddingHorizontal: 24,
      paddingVertical: 32,
      paddingBottom: 24,
    },
    titleContainer: {
      flexDirection: "row",
      alignItems: "center",
      marginBottom: 20,
    },
    iconContainer: {
      width: 56,
      height: 56,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
      marginRight: 16,
    },
    logoImage: {
      width: 56,
      height: 56,
      borderRadius: 16,
      marginRight: 16,
    },
    titleTextContainer: {
      flex: 1,
    },
    title: {
      fontSize: 32,
      fontWeight: "700",
      letterSpacing: -1,
      marginBottom: 4,
      color: colors.text,
    },
    subtitle: {
      fontSize: 17,
      fontWeight: "500",
      color: colors.textMuted,
    },
    progressContainer: {
      marginTop: 8,
    },
    progressBarContainer: {
      flexDirection: "row",
      alignItems: "center",
      gap: 16,
    },
    progressBar: {
      flex: 1,
      height: 12,
      borderRadius: 6,
      overflow: "hidden",
      backgroundColor: colors.border,
    },
    progressFill: {
      height: "100%",
      borderRadius: 6,
    },
    progressText: {
      fontSize: 16,
      fontWeight: "700",
      minWidth: 40,
      textAlign: "right",
      color: colors.success,
    },
    inputSection: {
      paddingHorizontal: 24,
      paddingBottom: 12,
    },
    inputWrapper: {
      flexDirection: "row",
      alignItems: "flex-end",
      gap: 16,
    },
    input: {
      flex: 1,
      borderWidth: 2,
      borderRadius: 20,
      paddingHorizontal: 20,
      paddingVertical: 16,
      fontSize: 17,
      maxHeight: 120,
      fontWeight: "500",
      backgroundColor: colors.backgrounds.input,
      borderColor: colors.border,
      color: colors.text,
    },
    inputFocused: {
      borderColor: colors.primary,
    },
    addButton: {
      width: 56,
      height: 56,
      borderRadius: 28,
      justifyContent: "center",
      alignItems: "center",
    },
    addButtonDisabled: {
      opacity: 0.5,
    },
    categoryContainer: {
      flexDirection: "row",
      paddingHorizontal: 20,
      paddingVertical: 16,
      gap: 8,
    },
    categoryTab: {
      flex: 1,
      paddingVertical: 10,
      paddingHorizontal: 8,
      borderRadius: 14,
      alignItems: "center",
      backgroundColor: colors.surface,
      borderWidth: 2,
      borderColor: colors.border,
    },
    categoryTabActive: {
      backgroundColor: colors.primary,
      borderColor: colors.primary,
    },
    categoryTabText: {
      fontSize: 13,
      fontWeight: "600",
      color: colors.text,
    },
    categoryTabTextActive: {
      color: "#fff",
    },
    todoList: {
      flex: 1,
    },
    todoListContent: {
      paddingHorizontal: 24,
      paddingBottom: 80,
    },
    emptyListContainer: {
      flexGrow: 1,
      justifyContent: "center",
    },
    todoItemWrapper: {
      marginVertical: 8,
    },
    todoItem: {
      flexDirection: "row",
      alignItems: "flex-start",
      padding: 16,
      paddingRight: 70,
      borderRadius: 16,
      shadowColor: "#000",
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 4,
      position: "relative",
      minHeight: 80,
    },
    checkbox: {
      marginRight: 14,
      marginTop: 2,
    },
    checkboxInner: {
      width: 26,
      height: 26,
      borderRadius: 13,
      justifyContent: "center",
      alignItems: "center",
    },
    todoContentWrapper: {
      flex: 1,
      flexDirection: "row",
      gap: 12,
    },
    todoTextContainer: {
      flex: 1,
    },
    todoHeader: {
      flexDirection: "row",
      justifyContent: "space-between",
      alignItems: "flex-start",
      marginBottom: 6,
      gap: 8,
    },
    todoText: {
      flex: 1,
      fontSize: 16,
      lineHeight: 22,
      fontWeight: "600",
      color: colors.text,
    },
    todoTextCompleted: {
      textDecorationLine: "line-through",
      color: colors.textMuted,
      opacity: 0.7,
    },
    completedBadgeContainer: {
      marginBottom: 6,
    },
    completedBadge: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
      alignSelf: "flex-start",
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
    },
    completedText: {
      fontSize: 12,
      fontWeight: "700",
      color: "#fff",
    },
    todoDescription: {
      fontSize: 14,
      lineHeight: 19,
      color: colors.text,
      opacity: 0.75,
      marginBottom: 8,
    },
    todoDescriptionCompleted: {
      opacity: 0.5,
      color: colors.textMuted,
    },
    priorityBadge: {
      paddingHorizontal: 7,
      paddingVertical: 3,
      borderRadius: 5,
      alignSelf: "flex-start",
    },
    priorityHigh: {
      backgroundColor: colors.danger,
    },
    priorityMedium: {
      backgroundColor: colors.warning,
    },
    priorityLow: {
      backgroundColor: colors.success,
    },
    priorityText: {
      fontSize: 9,
      fontWeight: "700",
      color: "#fff",
      letterSpacing: 0.4,
    },
    todoMetaRow: {
      flexDirection: "row",
      gap: 12,
      flexWrap: "wrap",
      marginTop: 2,
    },
    metaItem: {
      flexDirection: "row",
      alignItems: "center",
      gap: 5,
    },
    metaText: {
      fontSize: 12,
      fontWeight: "500",
      color: colors.textMuted,
    },
    todoRightSection: {
      position: "absolute",
      top: 12,
      right: 12,
    },
    todoActionsRow: {
      position: "absolute",
      bottom: 12,
      right: 12,
      flexDirection: "row",
      gap: 6,
    },
    todoActionsColumn: {
      flexDirection: "column",
      gap: 6,
      justifyContent: "center",
    },
    actionButton: {
      width: 32,
      height: 32,
      borderRadius: 16,
      justifyContent: "center",
      alignItems: "center",
    },
    editContainer: {
      flex: 1,
    },
    editInput: {
      borderWidth: 2,
      borderRadius: 16,
      paddingHorizontal: 16,
      paddingVertical: 12,
      fontSize: 17,
      fontWeight: "500",
      marginBottom: 16,
      backgroundColor: colors.backgrounds.editInput,
      borderColor: colors.primary,
      color: colors.text,
    },
    editButtons: {
      flexDirection: "row",
      gap: 12,
    },
    editButton: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 12,
    },
    editButtonText: {
      color: "#ffffff",
      fontSize: 14,
      fontWeight: "600",
    },
    emptyContainer: {
      alignItems: "center",
      justifyContent: "center",
      paddingVertical: 80,
    },
    emptyIconContainer: {
      width: 120,
      height: 120,
      borderRadius: 60,
      justifyContent: "center",
      alignItems: "center",
      marginBottom: 24,
    },
    emptyLogoImage: {
      width: 100,
      height: 100,
      borderRadius: 20,
    },
    emptyText: {
      fontSize: 24,
      fontWeight: "700",
      marginBottom: 8,
      color: colors.text,
    },
    emptySubtext: {
      fontSize: 17,
      textAlign: "center",
      paddingHorizontal: 40,
      lineHeight: 24,
      color: colors.textMuted,
    },
    fab: {
      position: "absolute",
      bottom: 24,
      right: 24,
      zIndex: 10,
    },
    fabGradient: {
      width: 60,
      height: 60,
      borderRadius: 30,
      justifyContent: "center",
      alignItems: "center",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 4,
      elevation: 8,
    },
    swipeBackground: {
      position: "absolute",
      top: 0,
      bottom: 0,
      justifyContent: "center",
      alignItems: "center",
      borderRadius: 16,
    },
    swipeLeft: {
      left: 0,
      right: 0,
      backgroundColor: "#EF4444",
      flexDirection: "row",
      justifyContent: "flex-end",
      paddingRight: 24,
    },
    swipeRight: {
      left: 0,
      right: 0,
      backgroundColor: "#10B981",
      flexDirection: "row",
      justifyContent: "flex-start",
      paddingLeft: 24,
    },
    swipeText: {
      color: "#FFFFFF",
      fontSize: 16,
      fontWeight: "600",
    },
  });

  return styles;
};
